// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.5.1 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for AdminUserRole.
const (
	AdminUserRoleAdmin AdminUserRole = "admin"
	AdminUserRoleUser  AdminUserRole = "user"
)

// Defines values for ErrorCode.
const (
	CANNOTBANADMIN      ErrorCode = "CANNOT_BAN_ADMIN"
	CANNOTHUGSELF       ErrorCode = "CANNOT_HUG_SELF"
	COOLDOWNACTIVE      ErrorCode = "COOLDOWN_ACTIVE"
	INSUFFICIENTBALANCE ErrorCode = "INSUFFICIENT_BALANCE"
	INVALIDCREDENTIALS  ErrorCode = "INVALID_CREDENTIALS"
	USERALREADYEXISTS   ErrorCode = "USER_ALREADY_EXISTS"
	USERBANNED          ErrorCode = "USER_BANNED"
	USERNOTFOUND        ErrorCode = "USER_NOT_FOUND"
	WEAKPASSWORD        ErrorCode = "WEAK_PASSWORD"
	WRONGPASSWORD       ErrorCode = "WRONG_PASSWORD"
)

// Defines values for Gender.
const (
	Female Gender = "female"
	Male   Gender = "male"
)

// Defines values for UserRole.
const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

// AdminStats defines model for AdminStats.
type AdminStats struct {
	BannedUsers int `json:"banned_users"`
	TotalUsers  int `json:"total_users"`
}

// AdminUser defines model for AdminUser.
type AdminUser struct {
	BannedAt *time.Time         `json:"banned_at"`
	Gender   *Gender            `json:"gender,omitempty"`
	Id       openapi_types.UUID `json:"id"`
	Role     AdminUserRole      `json:"role"`
	Username string             `json:"username"`
}

// AdminUserRole defines model for AdminUser.Role.
type AdminUserRole string

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Token string `json:"token"`
	User  User   `json:"user"`
}

// Balance defines model for Balance.
type Balance struct {
	Amount int                `json:"amount"`
	UserId openapi_types.UUID `json:"user_id"`
}

// CooldownInfo defines model for CooldownInfo.
type CooldownInfo struct {
	CanHug           bool               `json:"can_hug"`
	CooldownSeconds  int                `json:"cooldown_seconds"`
	GiverId          openapi_types.UUID `json:"giver_id"`
	ReceiverId       openapi_types.UUID `json:"receiver_id"`
	RemainingSeconds int                `json:"remaining_seconds"`
}

// DailyRewardResponse defines model for DailyRewardResponse.
type DailyRewardResponse struct {
	AlreadyClaimed *bool `json:"already_claimed,omitempty"`
	Amount         int   `json:"amount"`
	NewBalance     int   `json:"new_balance"`
	StreakDays     int   `json:"streak_days"`
}

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// Gender defines model for Gender.
type Gender string

// Hug defines model for Hug.
type Hug struct {
	CreatedAt  time.Time          `json:"created_at"`
	GiverId    openapi_types.UUID `json:"giver_id"`
	Id         openapi_types.UUID `json:"id"`
	ReceiverId openapi_types.UUID `json:"receiver_id"`
}

// HugActivityItem defines model for HugActivityItem.
type HugActivityItem struct {
	Count     int       `json:"count"`
	Timestamp time.Time `json:"timestamp"`
}

// HugFeedItem defines model for HugFeedItem.
type HugFeedItem struct {
	CreatedAt        time.Time          `json:"created_at"`
	GiverGender      *Gender            `json:"giver_gender,omitempty"`
	GiverId          openapi_types.UUID `json:"giver_id"`
	GiverUsername    string             `json:"giver_username"`
	Id               openapi_types.UUID `json:"id"`
	ReceiverId       openapi_types.UUID `json:"receiver_id"`
	ReceiverUsername string             `json:"receiver_username"`
}

// LeaderboardEntry defines model for LeaderboardEntry.
type LeaderboardEntry struct {
	HugsGiven    int                `json:"hugs_given"`
	HugsReceived int                `json:"hugs_received"`
	Rank         string             `json:"rank"`
	TotalHugs    int                `json:"total_hugs"`
	UserId       openapi_types.UUID `json:"user_id"`
	Username     string             `json:"username"`
}

// User defines model for User.
type User struct {
	Gender   *Gender            `json:"gender,omitempty"`
	Id       openapi_types.UUID `json:"id"`
	Role     UserRole           `json:"role"`
	Username string             `json:"username"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserListItem defines model for UserListItem.
type UserListItem struct {
	Gender   *Gender            `json:"gender,omitempty"`
	Id       openapi_types.UUID `json:"id"`
	Role     string             `json:"role"`
	Username string             `json:"username"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	Balance        *int               `json:"balance,omitempty"`
	Gender         *Gender            `json:"gender,omitempty"`
	HugsGiven      int                `json:"hugs_given"`
	HugsReceived   int                `json:"hugs_received"`
	Id             openapi_types.UUID `json:"id"`
	MutualGiven    *int               `json:"mutual_given,omitempty"`
	MutualReceived *int               `json:"mutual_received,omitempty"`
	MutualTotal    *int               `json:"mutual_total,omitempty"`
	Rank           string             `json:"rank"`
	Role           string             `json:"role"`
	TotalHugs      int                `json:"total_hugs"`
	Username       string             `json:"username"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetAdminUsersParams defines parameters for GetAdminUsers.
type GetAdminUsersParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// AdminUpdateGenderJSONBody defines parameters for AdminUpdateGender.
type AdminUpdateGenderJSONBody struct {
	Gender *Gender `json:"gender,omitempty"`
}

// AdminUpdatePasswordJSONBody defines parameters for AdminUpdatePassword.
type AdminUpdatePasswordJSONBody struct {
	Password string `json:"password"`
}

// AdminUpdateUsernameJSONBody defines parameters for AdminUpdateUsername.
type AdminUpdateUsernameJSONBody struct {
	Username string `json:"username"`
}

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// RefreshTokenParams defines parameters for RefreshToken.
type RefreshTokenParams struct {
	RefreshToken string `form:"refresh_token" json:"refresh_token"`
}

// RegisterUserJSONBody defines parameters for RegisterUser.
type RegisterUserJSONBody struct {
	Gender *Gender `json:"gender,omitempty"`

	// Password Password must be 8-128 characters, contain at least one letter, one digit, and one special character
	Password string `json:"password"`

	// Username Username must be 3-32 characters, start with a letter, and contain only letters, numbers, and underscores
	Username string `json:"username"`
}

// GetHugsFeedParams defines parameters for GetHugsFeed.
type GetHugsFeedParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetLeaderboardParams defines parameters for GetLeaderboard.
type GetLeaderboardParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ChangePasswordJSONBody defines parameters for ChangePassword.
type ChangePasswordJSONBody struct {
	// NewPassword Password must be 8-128 characters, contain at least one letter, one digit, and one special character
	NewPassword string `json:"new_password"`
	OldPassword string `json:"old_password"`
}

// UpdateUserSettingsJSONBody defines parameters for UpdateUserSettings.
type UpdateUserSettingsJSONBody struct {
	Gender *Gender `json:"gender,omitempty"`
}

// SearchUsersParams defines parameters for SearchUsers.
type SearchUsersParams struct {
	Q      *string `form:"q,omitempty" json:"q,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// AdminUpdateGenderJSONRequestBody defines body for AdminUpdateGender for application/json ContentType.
type AdminUpdateGenderJSONRequestBody AdminUpdateGenderJSONBody

// AdminUpdatePasswordJSONRequestBody defines body for AdminUpdatePassword for application/json ContentType.
type AdminUpdatePasswordJSONRequestBody AdminUpdatePasswordJSONBody

// AdminUpdateUsernameJSONRequestBody defines body for AdminUpdateUsername for application/json ContentType.
type AdminUpdateUsernameJSONRequestBody AdminUpdateUsernameJSONBody

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody RegisterUserJSONBody

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody ChangePasswordJSONBody

// UpdateUserSettingsJSONRequestBody defines body for UpdateUserSettings for application/json ContentType.
type UpdateUserSettingsJSONRequestBody UpdateUserSettingsJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// admin ping (testing auth)
	// (GET /admin/ping)
	GetAdminPing(ctx echo.Context) error
	// Get admin dashboard stats
	// (GET /admin/stats)
	GetAdminStats(ctx echo.Context) error
	// List all users for admin panel
	// (GET /admin/users)
	GetAdminUsers(ctx echo.Context, params GetAdminUsersParams) error
	// Unban a user
	// (DELETE /admin/users/{userId}/ban)
	UnbanUser(ctx echo.Context, userId openapi_types.UUID) error
	// Ban a user
	// (PUT /admin/users/{userId}/ban)
	BanUser(ctx echo.Context, userId openapi_types.UUID) error
	// Change a user's gender
	// (PUT /admin/users/{userId}/gender)
	AdminUpdateGender(ctx echo.Context, userId openapi_types.UUID) error
	// Change a user's password
	// (PUT /admin/users/{userId}/password)
	AdminUpdatePassword(ctx echo.Context, userId openapi_types.UUID) error
	// Change a user's username
	// (PUT /admin/users/{userId}/username)
	AdminUpdateUsername(ctx echo.Context, userId openapi_types.UUID) error
	// Login
	// (POST /auth/login)
	Login(ctx echo.Context) error
	// Logout and clear refresh token cookie
	// (POST /auth/logout)
	Logout(ctx echo.Context) error
	// Refresh access token using refresh token cookie
	// (POST /auth/refresh)
	RefreshToken(ctx echo.Context, params RefreshTokenParams) error
	// Register a new user
	// (POST /auth/register)
	RegisterUser(ctx echo.Context) error
	// Get current user balance
	// (GET /balance)
	GetBalance(ctx echo.Context) error
	// Claim daily reward
	// (POST /daily-reward)
	ClaimDailyReward(ctx echo.Context) error
	// Get hug activity for the last 24 hours grouped by hour
	// (GET /hugs/activity)
	GetHugActivity(ctx echo.Context) error
	// Check cooldown status for a user pair
	// (GET /hugs/cooldown/{userId})
	GetCooldown(ctx echo.Context, userId openapi_types.UUID) error
	// Upgrade (reduce) cooldown by spending balance
	// (POST /hugs/cooldown/{userId}/upgrade)
	UpgradeCooldown(ctx echo.Context, userId openapi_types.UUID) error
	// Get recent hugs feed
	// (GET /hugs/feed)
	GetHugsFeed(ctx echo.Context, params GetHugsFeedParams) error
	// Get hug history for current user
	// (GET /hugs/history)
	GetHugHistory(ctx echo.Context) error
	// Send a hug to a user
	// (POST /hugs/{userId})
	SendHug(ctx echo.Context, userId openapi_types.UUID) error
	// Get leaderboard
	// (GET /leaderboard)
	GetLeaderboard(ctx echo.Context, params GetLeaderboardParams) error
	// Ping endpoint
	// (GET /ping)
	GetPing(ctx echo.Context) error
	// Get current user info
	// (GET /users/me)
	GetCurrentUser(ctx echo.Context) error
	// Change current user password
	// (PUT /users/me/password)
	ChangePassword(ctx echo.Context) error
	// Update current user settings
	// (PUT /users/me/settings)
	UpdateUserSettings(ctx echo.Context) error
	// Search users by username
	// (GET /users/search)
	SearchUsers(ctx echo.Context, params SearchUsersParams) error
	// Get user profile with stats
	// (GET /users/{userId}/profile)
	GetUserProfile(ctx echo.Context, userId openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAdminPing converts echo context to params.
func (w *ServerInterfaceWrapper) GetAdminPing(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAdminPing(ctx)
	return err
}

// GetAdminStats converts echo context to params.
func (w *ServerInterfaceWrapper) GetAdminStats(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAdminStats(ctx)
	return err
}

// GetAdminUsers converts echo context to params.
func (w *ServerInterfaceWrapper) GetAdminUsers(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"admin"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAdminUsersParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAdminUsers(ctx, params)
	return err
}

// UnbanUser converts echo context to params.
func (w *ServerInterfaceWrapper) UnbanUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{"admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UnbanUser(ctx, userId)
	return err
}

// BanUser converts echo context to params.
func (w *ServerInterfaceWrapper) BanUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{"admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.BanUser(ctx, userId)
	return err
}

// AdminUpdateGender converts echo context to params.
func (w *ServerInterfaceWrapper) AdminUpdateGender(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{"admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AdminUpdateGender(ctx, userId)
	return err
}

// AdminUpdatePassword converts echo context to params.
func (w *ServerInterfaceWrapper) AdminUpdatePassword(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{"admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AdminUpdatePassword(ctx, userId)
	return err
}

// AdminUpdateUsername converts echo context to params.
func (w *ServerInterfaceWrapper) AdminUpdateUsername(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{"admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AdminUpdateUsername(ctx, userId)
	return err
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx)
	return err
}

// RefreshToken converts echo context to params.
func (w *ServerInterfaceWrapper) RefreshToken(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params RefreshTokenParams

	if cookie, err := ctx.Cookie("refresh_token"); err == nil {

		var value string
		err = runtime.BindStyledParameterWithOptions("simple", "refresh_token", cookie.Value, &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationCookie, Explode: true, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter refresh_token: %s", err))
		}
		params.RefreshToken = value

	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Query argument refresh_token is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RefreshToken(ctx, params)
	return err
}

// RegisterUser converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RegisterUser(ctx)
	return err
}

// GetBalance converts echo context to params.
func (w *ServerInterfaceWrapper) GetBalance(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBalance(ctx)
	return err
}

// ClaimDailyReward converts echo context to params.
func (w *ServerInterfaceWrapper) ClaimDailyReward(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ClaimDailyReward(ctx)
	return err
}

// GetHugActivity converts echo context to params.
func (w *ServerInterfaceWrapper) GetHugActivity(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHugActivity(ctx)
	return err
}

// GetCooldown converts echo context to params.
func (w *ServerInterfaceWrapper) GetCooldown(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCooldown(ctx, userId)
	return err
}

// UpgradeCooldown converts echo context to params.
func (w *ServerInterfaceWrapper) UpgradeCooldown(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpgradeCooldown(ctx, userId)
	return err
}

// GetHugsFeed converts echo context to params.
func (w *ServerInterfaceWrapper) GetHugsFeed(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHugsFeedParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHugsFeed(ctx, params)
	return err
}

// GetHugHistory converts echo context to params.
func (w *ServerInterfaceWrapper) GetHugHistory(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHugHistory(ctx)
	return err
}

// SendHug converts echo context to params.
func (w *ServerInterfaceWrapper) SendHug(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SendHug(ctx, userId)
	return err
}

// GetLeaderboard converts echo context to params.
func (w *ServerInterfaceWrapper) GetLeaderboard(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLeaderboardParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLeaderboard(ctx, params)
	return err
}

// GetPing converts echo context to params.
func (w *ServerInterfaceWrapper) GetPing(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPing(ctx)
	return err
}

// GetCurrentUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetCurrentUser(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCurrentUser(ctx)
	return err
}

// ChangePassword converts echo context to params.
func (w *ServerInterfaceWrapper) ChangePassword(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ChangePassword(ctx)
	return err
}

// UpdateUserSettings converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUserSettings(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateUserSettings(ctx)
	return err
}

// SearchUsers converts echo context to params.
func (w *ServerInterfaceWrapper) SearchUsers(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchUsersParams
	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", ctx.QueryParams(), &params.Q)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchUsers(ctx, params)
	return err
}

// GetUserProfile converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserProfile(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{"user", "admin"})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserProfile(ctx, userId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/admin/ping", wrapper.GetAdminPing)
	router.GET(baseURL+"/admin/stats", wrapper.GetAdminStats)
	router.GET(baseURL+"/admin/users", wrapper.GetAdminUsers)
	router.DELETE(baseURL+"/admin/users/:userId/ban", wrapper.UnbanUser)
	router.PUT(baseURL+"/admin/users/:userId/ban", wrapper.BanUser)
	router.PUT(baseURL+"/admin/users/:userId/gender", wrapper.AdminUpdateGender)
	router.PUT(baseURL+"/admin/users/:userId/password", wrapper.AdminUpdatePassword)
	router.PUT(baseURL+"/admin/users/:userId/username", wrapper.AdminUpdateUsername)
	router.POST(baseURL+"/auth/login", wrapper.Login)
	router.POST(baseURL+"/auth/logout", wrapper.Logout)
	router.POST(baseURL+"/auth/refresh", wrapper.RefreshToken)
	router.POST(baseURL+"/auth/register", wrapper.RegisterUser)
	router.GET(baseURL+"/balance", wrapper.GetBalance)
	router.POST(baseURL+"/daily-reward", wrapper.ClaimDailyReward)
	router.GET(baseURL+"/hugs/activity", wrapper.GetHugActivity)
	router.GET(baseURL+"/hugs/cooldown/:userId", wrapper.GetCooldown)
	router.POST(baseURL+"/hugs/cooldown/:userId/upgrade", wrapper.UpgradeCooldown)
	router.GET(baseURL+"/hugs/feed", wrapper.GetHugsFeed)
	router.GET(baseURL+"/hugs/history", wrapper.GetHugHistory)
	router.POST(baseURL+"/hugs/:userId", wrapper.SendHug)
	router.GET(baseURL+"/leaderboard", wrapper.GetLeaderboard)
	router.GET(baseURL+"/ping", wrapper.GetPing)
	router.GET(baseURL+"/users/me", wrapper.GetCurrentUser)
	router.PUT(baseURL+"/users/me/password", wrapper.ChangePassword)
	router.PUT(baseURL+"/users/me/settings", wrapper.UpdateUserSettings)
	router.GET(baseURL+"/users/search", wrapper.SearchUsers)
	router.GET(baseURL+"/users/:userId/profile", wrapper.GetUserProfile)

}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type ForbiddenJSONResponse Error

type NotFoundJSONResponse Error

type TooManyRequestsJSONResponse Error

type UnauthorizedJSONResponse Error

type GetAdminPingRequestObject struct {
}

type GetAdminPingResponseObject interface {
	VisitGetAdminPingResponse(w http.ResponseWriter) error
}

type GetAdminPing200JSONResponse struct {
	Secret string `json:"secret"`
}

func (response GetAdminPing200JSONResponse) VisitGetAdminPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminPing401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAdminPing401JSONResponse) VisitGetAdminPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminPing403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetAdminPing403JSONResponse) VisitGetAdminPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminStatsRequestObject struct {
}

type GetAdminStatsResponseObject interface {
	VisitGetAdminStatsResponse(w http.ResponseWriter) error
}

type GetAdminStats200JSONResponse AdminStats

func (response GetAdminStats200JSONResponse) VisitGetAdminStatsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminStats401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAdminStats401JSONResponse) VisitGetAdminStatsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminStats403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetAdminStats403JSONResponse) VisitGetAdminStatsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminUsersRequestObject struct {
	Params GetAdminUsersParams
}

type GetAdminUsersResponseObject interface {
	VisitGetAdminUsersResponse(w http.ResponseWriter) error
}

type GetAdminUsers200JSONResponse []AdminUser

func (response GetAdminUsers200JSONResponse) VisitGetAdminUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminUsers401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetAdminUsers401JSONResponse) VisitGetAdminUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetAdminUsers403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetAdminUsers403JSONResponse) VisitGetAdminUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UnbanUserRequestObject struct {
	UserId openapi_types.UUID `json:"userId"`
}

type UnbanUserResponseObject interface {
	VisitUnbanUserResponse(w http.ResponseWriter) error
}

type UnbanUser200JSONResponse AdminUser

func (response UnbanUser200JSONResponse) VisitUnbanUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UnbanUser401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UnbanUser401JSONResponse) VisitUnbanUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UnbanUser403JSONResponse struct{ ForbiddenJSONResponse }

func (response UnbanUser403JSONResponse) VisitUnbanUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UnbanUser404JSONResponse struct{ NotFoundJSONResponse }

func (response UnbanUser404JSONResponse) VisitUnbanUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type BanUserRequestObject struct {
	UserId openapi_types.UUID `json:"userId"`
}

type BanUserResponseObject interface {
	VisitBanUserResponse(w http.ResponseWriter) error
}

type BanUser200JSONResponse AdminUser

func (response BanUser200JSONResponse) VisitBanUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type BanUser400JSONResponse struct{ BadRequestJSONResponse }

func (response BanUser400JSONResponse) VisitBanUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type BanUser401JSONResponse struct{ UnauthorizedJSONResponse }

func (response BanUser401JSONResponse) VisitBanUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type BanUser403JSONResponse struct{ ForbiddenJSONResponse }

func (response BanUser403JSONResponse) VisitBanUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type BanUser404JSONResponse struct{ NotFoundJSONResponse }

func (response BanUser404JSONResponse) VisitBanUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AdminUpdateGenderRequestObject struct {
	UserId openapi_types.UUID `json:"userId"`
	Body   *AdminUpdateGenderJSONRequestBody
}

type AdminUpdateGenderResponseObject interface {
	VisitAdminUpdateGenderResponse(w http.ResponseWriter) error
}

type AdminUpdateGender200JSONResponse AdminUser

func (response AdminUpdateGender200JSONResponse) VisitAdminUpdateGenderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AdminUpdateGender400JSONResponse struct{ BadRequestJSONResponse }

func (response AdminUpdateGender400JSONResponse) VisitAdminUpdateGenderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AdminUpdateGender401JSONResponse struct{ UnauthorizedJSONResponse }

func (response AdminUpdateGender401JSONResponse) VisitAdminUpdateGenderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type AdminUpdateGender403JSONResponse struct{ ForbiddenJSONResponse }

func (response AdminUpdateGender403JSONResponse) VisitAdminUpdateGenderResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type AdminUpdatePasswordRequestObject struct {
	UserId openapi_types.UUID `json:"userId"`
	Body   *AdminUpdatePasswordJSONRequestBody
}

type AdminUpdatePasswordResponseObject interface {
	VisitAdminUpdatePasswordResponse(w http.ResponseWriter) error
}

type AdminUpdatePassword200JSONResponse struct {
	Message string `json:"message"`
}

func (response AdminUpdatePassword200JSONResponse) VisitAdminUpdatePasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AdminUpdatePassword400JSONResponse struct{ BadRequestJSONResponse }

func (response AdminUpdatePassword400JSONResponse) VisitAdminUpdatePasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AdminUpdatePassword401JSONResponse struct{ UnauthorizedJSONResponse }

func (response AdminUpdatePassword401JSONResponse) VisitAdminUpdatePasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type AdminUpdatePassword403JSONResponse struct{ ForbiddenJSONResponse }

func (response AdminUpdatePassword403JSONResponse) VisitAdminUpdatePasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type AdminUpdateUsernameRequestObject struct {
	UserId openapi_types.UUID `json:"userId"`
	Body   *AdminUpdateUsernameJSONRequestBody
}

type AdminUpdateUsernameResponseObject interface {
	VisitAdminUpdateUsernameResponse(w http.ResponseWriter) error
}

type AdminUpdateUsername200JSONResponse AdminUser

func (response AdminUpdateUsername200JSONResponse) VisitAdminUpdateUsernameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AdminUpdateUsername400JSONResponse struct{ BadRequestJSONResponse }

func (response AdminUpdateUsername400JSONResponse) VisitAdminUpdateUsernameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AdminUpdateUsername401JSONResponse struct{ UnauthorizedJSONResponse }

func (response AdminUpdateUsername401JSONResponse) VisitAdminUpdateUsernameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type AdminUpdateUsername403JSONResponse struct{ ForbiddenJSONResponse }

func (response AdminUpdateUsername403JSONResponse) VisitAdminUpdateUsernameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type AdminUpdateUsername409JSONResponse struct{ ConflictJSONResponse }

func (response AdminUpdateUsername409JSONResponse) VisitAdminUpdateUsernameResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	SetCookie string
}

type Login200JSONResponse struct {
	Body    AuthResponse
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type Login400JSONResponse struct{ BadRequestJSONResponse }

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Login401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Login403JSONResponse struct{ ForbiddenJSONResponse }

func (response Login403JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout200ResponseHeaders struct {
	SetCookie string
}

type Logout200JSONResponse struct {
	Body struct {
		Message string `json:"message"`
	}
	Headers Logout200ResponseHeaders
}

func (response Logout200JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type RefreshTokenRequestObject struct {
	Params RefreshTokenParams
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200ResponseHeaders struct {
	SetCookie string
}

type RefreshToken200JSONResponse struct {
	Body struct {
		Token string `json:"token"`
	}
	Headers RefreshToken200ResponseHeaders
}

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type RefreshToken401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RefreshToken401JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RefreshToken403JSONResponse struct{ ForbiddenJSONResponse }

func (response RefreshToken403JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUserRequestObject struct {
	Body *RegisterUserJSONRequestBody
}

type RegisterUserResponseObject interface {
	VisitRegisterUserResponse(w http.ResponseWriter) error
}

type RegisterUser201ResponseHeaders struct {
	SetCookie string
}

type RegisterUser201JSONResponse struct {
	Body    AuthResponse
	Headers RegisterUser201ResponseHeaders
}

func (response RegisterUser201JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response.Body)
}

type RegisterUser400JSONResponse struct{ BadRequestJSONResponse }

func (response RegisterUser400JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser409JSONResponse struct{ ConflictJSONResponse }

func (response RegisterUser409JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetBalanceRequestObject struct {
}

type GetBalanceResponseObject interface {
	VisitGetBalanceResponse(w http.ResponseWriter) error
}

type GetBalance200JSONResponse Balance

func (response GetBalance200JSONResponse) VisitGetBalanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetBalance401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetBalance401JSONResponse) VisitGetBalanceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ClaimDailyRewardRequestObject struct {
}

type ClaimDailyRewardResponseObject interface {
	VisitClaimDailyRewardResponse(w http.ResponseWriter) error
}

type ClaimDailyReward200JSONResponse DailyRewardResponse

func (response ClaimDailyReward200JSONResponse) VisitClaimDailyRewardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ClaimDailyReward401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ClaimDailyReward401JSONResponse) VisitClaimDailyRewardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ClaimDailyReward429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response ClaimDailyReward429JSONResponse) VisitClaimDailyRewardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type GetHugActivityRequestObject struct {
}

type GetHugActivityResponseObject interface {
	VisitGetHugActivityResponse(w http.ResponseWriter) error
}

type GetHugActivity200JSONResponse []HugActivityItem

func (response GetHugActivity200JSONResponse) VisitGetHugActivityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHugActivity401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetHugActivity401JSONResponse) VisitGetHugActivityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetCooldownRequestObject struct {
	UserId openapi_types.UUID `json:"userId"`
}

type GetCooldownResponseObject interface {
	VisitGetCooldownResponse(w http.ResponseWriter) error
}

type GetCooldown200JSONResponse CooldownInfo

func (response GetCooldown200JSONResponse) VisitGetCooldownResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCooldown401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetCooldown401JSONResponse) VisitGetCooldownResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpgradeCooldownRequestObject struct {
	UserId openapi_types.UUID `json:"userId"`
}

type UpgradeCooldownResponseObject interface {
	VisitUpgradeCooldownResponse(w http.ResponseWriter) error
}

type UpgradeCooldown200JSONResponse CooldownInfo

func (response UpgradeCooldown200JSONResponse) VisitUpgradeCooldownResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpgradeCooldown400JSONResponse struct{ BadRequestJSONResponse }

func (response UpgradeCooldown400JSONResponse) VisitUpgradeCooldownResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpgradeCooldown401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpgradeCooldown401JSONResponse) VisitUpgradeCooldownResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetHugsFeedRequestObject struct {
	Params GetHugsFeedParams
}

type GetHugsFeedResponseObject interface {
	VisitGetHugsFeedResponse(w http.ResponseWriter) error
}

type GetHugsFeed200JSONResponse []HugFeedItem

func (response GetHugsFeed200JSONResponse) VisitGetHugsFeedResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHugsFeed401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetHugsFeed401JSONResponse) VisitGetHugsFeedResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetHugHistoryRequestObject struct {
}

type GetHugHistoryResponseObject interface {
	VisitGetHugHistoryResponse(w http.ResponseWriter) error
}

type GetHugHistory200JSONResponse []HugFeedItem

func (response GetHugHistory200JSONResponse) VisitGetHugHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHugHistory401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetHugHistory401JSONResponse) VisitGetHugHistoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SendHugRequestObject struct {
	UserId openapi_types.UUID `json:"userId"`
}

type SendHugResponseObject interface {
	VisitSendHugResponse(w http.ResponseWriter) error
}

type SendHug201JSONResponse Hug

func (response SendHug201JSONResponse) VisitSendHugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type SendHug400JSONResponse struct{ BadRequestJSONResponse }

func (response SendHug400JSONResponse) VisitSendHugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SendHug401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SendHug401JSONResponse) VisitSendHugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SendHug404JSONResponse struct{ NotFoundJSONResponse }

func (response SendHug404JSONResponse) VisitSendHugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SendHug429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response SendHug429JSONResponse) VisitSendHugResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type GetLeaderboardRequestObject struct {
	Params GetLeaderboardParams
}

type GetLeaderboardResponseObject interface {
	VisitGetLeaderboardResponse(w http.ResponseWriter) error
}

type GetLeaderboard200JSONResponse []LeaderboardEntry

func (response GetLeaderboard200JSONResponse) VisitGetLeaderboardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLeaderboard401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetLeaderboard401JSONResponse) VisitGetLeaderboardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetPingRequestObject struct {
}

type GetPingResponseObject interface {
	VisitGetPingResponse(w http.ResponseWriter) error
}

type GetPing200JSONResponse struct {
	Status string `json:"status"`
}

func (response GetPing200JSONResponse) VisitGetPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUserRequestObject struct {
}

type GetCurrentUserResponseObject interface {
	VisitGetCurrentUserResponse(w http.ResponseWriter) error
}

type GetCurrentUser200JSONResponse User

func (response GetCurrentUser200JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUser401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetCurrentUser401JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUser404JSONResponse struct{ NotFoundJSONResponse }

func (response GetCurrentUser404JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ChangePasswordRequestObject struct {
	Body *ChangePasswordJSONRequestBody
}

type ChangePasswordResponseObject interface {
	VisitChangePasswordResponse(w http.ResponseWriter) error
}

type ChangePassword200JSONResponse struct {
	Message string `json:"message"`
}

func (response ChangePassword200JSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ChangePassword400JSONResponse struct{ BadRequestJSONResponse }

func (response ChangePassword400JSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ChangePassword401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ChangePassword401JSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateUserSettingsRequestObject struct {
	Body *UpdateUserSettingsJSONRequestBody
}

type UpdateUserSettingsResponseObject interface {
	VisitUpdateUserSettingsResponse(w http.ResponseWriter) error
}

type UpdateUserSettings200JSONResponse User

func (response UpdateUserSettings200JSONResponse) VisitUpdateUserSettingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateUserSettings400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateUserSettings400JSONResponse) VisitUpdateUserSettingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateUserSettings401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateUserSettings401JSONResponse) VisitUpdateUserSettingsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SearchUsersRequestObject struct {
	Params SearchUsersParams
}

type SearchUsersResponseObject interface {
	VisitSearchUsersResponse(w http.ResponseWriter) error
}

type SearchUsers200JSONResponse []UserListItem

func (response SearchUsers200JSONResponse) VisitSearchUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchUsers401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SearchUsers401JSONResponse) VisitSearchUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetUserProfileRequestObject struct {
	UserId openapi_types.UUID `json:"userId"`
}

type GetUserProfileResponseObject interface {
	VisitGetUserProfileResponse(w http.ResponseWriter) error
}

type GetUserProfile200JSONResponse UserProfile

func (response GetUserProfile200JSONResponse) VisitGetUserProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetUserProfile401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetUserProfile401JSONResponse) VisitGetUserProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetUserProfile404JSONResponse struct{ NotFoundJSONResponse }

func (response GetUserProfile404JSONResponse) VisitGetUserProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// admin ping (testing auth)
	// (GET /admin/ping)
	GetAdminPing(ctx context.Context, request GetAdminPingRequestObject) (GetAdminPingResponseObject, error)
	// Get admin dashboard stats
	// (GET /admin/stats)
	GetAdminStats(ctx context.Context, request GetAdminStatsRequestObject) (GetAdminStatsResponseObject, error)
	// List all users for admin panel
	// (GET /admin/users)
	GetAdminUsers(ctx context.Context, request GetAdminUsersRequestObject) (GetAdminUsersResponseObject, error)
	// Unban a user
	// (DELETE /admin/users/{userId}/ban)
	UnbanUser(ctx context.Context, request UnbanUserRequestObject) (UnbanUserResponseObject, error)
	// Ban a user
	// (PUT /admin/users/{userId}/ban)
	BanUser(ctx context.Context, request BanUserRequestObject) (BanUserResponseObject, error)
	// Change a user's gender
	// (PUT /admin/users/{userId}/gender)
	AdminUpdateGender(ctx context.Context, request AdminUpdateGenderRequestObject) (AdminUpdateGenderResponseObject, error)
	// Change a user's password
	// (PUT /admin/users/{userId}/password)
	AdminUpdatePassword(ctx context.Context, request AdminUpdatePasswordRequestObject) (AdminUpdatePasswordResponseObject, error)
	// Change a user's username
	// (PUT /admin/users/{userId}/username)
	AdminUpdateUsername(ctx context.Context, request AdminUpdateUsernameRequestObject) (AdminUpdateUsernameResponseObject, error)
	// Login
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout and clear refresh token cookie
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Refresh access token using refresh token cookie
	// (POST /auth/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// Register a new user
	// (POST /auth/register)
	RegisterUser(ctx context.Context, request RegisterUserRequestObject) (RegisterUserResponseObject, error)
	// Get current user balance
	// (GET /balance)
	GetBalance(ctx context.Context, request GetBalanceRequestObject) (GetBalanceResponseObject, error)
	// Claim daily reward
	// (POST /daily-reward)
	ClaimDailyReward(ctx context.Context, request ClaimDailyRewardRequestObject) (ClaimDailyRewardResponseObject, error)
	// Get hug activity for the last 24 hours grouped by hour
	// (GET /hugs/activity)
	GetHugActivity(ctx context.Context, request GetHugActivityRequestObject) (GetHugActivityResponseObject, error)
	// Check cooldown status for a user pair
	// (GET /hugs/cooldown/{userId})
	GetCooldown(ctx context.Context, request GetCooldownRequestObject) (GetCooldownResponseObject, error)
	// Upgrade (reduce) cooldown by spending balance
	// (POST /hugs/cooldown/{userId}/upgrade)
	UpgradeCooldown(ctx context.Context, request UpgradeCooldownRequestObject) (UpgradeCooldownResponseObject, error)
	// Get recent hugs feed
	// (GET /hugs/feed)
	GetHugsFeed(ctx context.Context, request GetHugsFeedRequestObject) (GetHugsFeedResponseObject, error)
	// Get hug history for current user
	// (GET /hugs/history)
	GetHugHistory(ctx context.Context, request GetHugHistoryRequestObject) (GetHugHistoryResponseObject, error)
	// Send a hug to a user
	// (POST /hugs/{userId})
	SendHug(ctx context.Context, request SendHugRequestObject) (SendHugResponseObject, error)
	// Get leaderboard
	// (GET /leaderboard)
	GetLeaderboard(ctx context.Context, request GetLeaderboardRequestObject) (GetLeaderboardResponseObject, error)
	// Ping endpoint
	// (GET /ping)
	GetPing(ctx context.Context, request GetPingRequestObject) (GetPingResponseObject, error)
	// Get current user info
	// (GET /users/me)
	GetCurrentUser(ctx context.Context, request GetCurrentUserRequestObject) (GetCurrentUserResponseObject, error)
	// Change current user password
	// (PUT /users/me/password)
	ChangePassword(ctx context.Context, request ChangePasswordRequestObject) (ChangePasswordResponseObject, error)
	// Update current user settings
	// (PUT /users/me/settings)
	UpdateUserSettings(ctx context.Context, request UpdateUserSettingsRequestObject) (UpdateUserSettingsResponseObject, error)
	// Search users by username
	// (GET /users/search)
	SearchUsers(ctx context.Context, request SearchUsersRequestObject) (SearchUsersResponseObject, error)
	// Get user profile with stats
	// (GET /users/{userId}/profile)
	GetUserProfile(ctx context.Context, request GetUserProfileRequestObject) (GetUserProfileResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetAdminPing operation middleware
func (sh *strictHandler) GetAdminPing(ctx echo.Context) error {
	var request GetAdminPingRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminPing(ctx.Request().Context(), request.(GetAdminPingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminPing")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAdminPingResponseObject); ok {
		return validResponse.VisitGetAdminPingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAdminStats operation middleware
func (sh *strictHandler) GetAdminStats(ctx echo.Context) error {
	var request GetAdminStatsRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminStats(ctx.Request().Context(), request.(GetAdminStatsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminStats")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAdminStatsResponseObject); ok {
		return validResponse.VisitGetAdminStatsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAdminUsers operation middleware
func (sh *strictHandler) GetAdminUsers(ctx echo.Context, params GetAdminUsersParams) error {
	var request GetAdminUsersRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAdminUsers(ctx.Request().Context(), request.(GetAdminUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAdminUsers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAdminUsersResponseObject); ok {
		return validResponse.VisitGetAdminUsersResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UnbanUser operation middleware
func (sh *strictHandler) UnbanUser(ctx echo.Context, userId openapi_types.UUID) error {
	var request UnbanUserRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UnbanUser(ctx.Request().Context(), request.(UnbanUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UnbanUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UnbanUserResponseObject); ok {
		return validResponse.VisitUnbanUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// BanUser operation middleware
func (sh *strictHandler) BanUser(ctx echo.Context, userId openapi_types.UUID) error {
	var request BanUserRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.BanUser(ctx.Request().Context(), request.(BanUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BanUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(BanUserResponseObject); ok {
		return validResponse.VisitBanUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminUpdateGender operation middleware
func (sh *strictHandler) AdminUpdateGender(ctx echo.Context, userId openapi_types.UUID) error {
	var request AdminUpdateGenderRequestObject

	request.UserId = userId

	var body AdminUpdateGenderJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AdminUpdateGender(ctx.Request().Context(), request.(AdminUpdateGenderRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminUpdateGender")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminUpdateGenderResponseObject); ok {
		return validResponse.VisitAdminUpdateGenderResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminUpdatePassword operation middleware
func (sh *strictHandler) AdminUpdatePassword(ctx echo.Context, userId openapi_types.UUID) error {
	var request AdminUpdatePasswordRequestObject

	request.UserId = userId

	var body AdminUpdatePasswordJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AdminUpdatePassword(ctx.Request().Context(), request.(AdminUpdatePasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminUpdatePassword")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminUpdatePasswordResponseObject); ok {
		return validResponse.VisitAdminUpdatePasswordResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AdminUpdateUsername operation middleware
func (sh *strictHandler) AdminUpdateUsername(ctx echo.Context, userId openapi_types.UUID) error {
	var request AdminUpdateUsernameRequestObject

	request.UserId = userId

	var body AdminUpdateUsernameJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AdminUpdateUsername(ctx.Request().Context(), request.(AdminUpdateUsernameRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminUpdateUsername")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AdminUpdateUsernameResponseObject); ok {
		return validResponse.VisitAdminUpdateUsernameResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Login operation middleware
func (sh *strictHandler) Login(ctx echo.Context) error {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx.Request().Context(), request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		return validResponse.VisitLoginResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx echo.Context) error {
	var request LogoutRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx.Request().Context(), request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		return validResponse.VisitLogoutResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(ctx echo.Context, params RefreshTokenParams) error {
	var request RefreshTokenRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx.Request().Context(), request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		return validResponse.VisitRefreshTokenResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RegisterUser operation middleware
func (sh *strictHandler) RegisterUser(ctx echo.Context) error {
	var request RegisterUserRequestObject

	var body RegisterUserJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterUser(ctx.Request().Context(), request.(RegisterUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RegisterUserResponseObject); ok {
		return validResponse.VisitRegisterUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetBalance operation middleware
func (sh *strictHandler) GetBalance(ctx echo.Context) error {
	var request GetBalanceRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetBalance(ctx.Request().Context(), request.(GetBalanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBalance")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetBalanceResponseObject); ok {
		return validResponse.VisitGetBalanceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ClaimDailyReward operation middleware
func (sh *strictHandler) ClaimDailyReward(ctx echo.Context) error {
	var request ClaimDailyRewardRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ClaimDailyReward(ctx.Request().Context(), request.(ClaimDailyRewardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ClaimDailyReward")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ClaimDailyRewardResponseObject); ok {
		return validResponse.VisitClaimDailyRewardResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetHugActivity operation middleware
func (sh *strictHandler) GetHugActivity(ctx echo.Context) error {
	var request GetHugActivityRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHugActivity(ctx.Request().Context(), request.(GetHugActivityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHugActivity")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHugActivityResponseObject); ok {
		return validResponse.VisitGetHugActivityResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCooldown operation middleware
func (sh *strictHandler) GetCooldown(ctx echo.Context, userId openapi_types.UUID) error {
	var request GetCooldownRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCooldown(ctx.Request().Context(), request.(GetCooldownRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCooldown")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCooldownResponseObject); ok {
		return validResponse.VisitGetCooldownResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpgradeCooldown operation middleware
func (sh *strictHandler) UpgradeCooldown(ctx echo.Context, userId openapi_types.UUID) error {
	var request UpgradeCooldownRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpgradeCooldown(ctx.Request().Context(), request.(UpgradeCooldownRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpgradeCooldown")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpgradeCooldownResponseObject); ok {
		return validResponse.VisitUpgradeCooldownResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetHugsFeed operation middleware
func (sh *strictHandler) GetHugsFeed(ctx echo.Context, params GetHugsFeedParams) error {
	var request GetHugsFeedRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHugsFeed(ctx.Request().Context(), request.(GetHugsFeedRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHugsFeed")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHugsFeedResponseObject); ok {
		return validResponse.VisitGetHugsFeedResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetHugHistory operation middleware
func (sh *strictHandler) GetHugHistory(ctx echo.Context) error {
	var request GetHugHistoryRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHugHistory(ctx.Request().Context(), request.(GetHugHistoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHugHistory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHugHistoryResponseObject); ok {
		return validResponse.VisitGetHugHistoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SendHug operation middleware
func (sh *strictHandler) SendHug(ctx echo.Context, userId openapi_types.UUID) error {
	var request SendHugRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SendHug(ctx.Request().Context(), request.(SendHugRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SendHug")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SendHugResponseObject); ok {
		return validResponse.VisitSendHugResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetLeaderboard operation middleware
func (sh *strictHandler) GetLeaderboard(ctx echo.Context, params GetLeaderboardParams) error {
	var request GetLeaderboardRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetLeaderboard(ctx.Request().Context(), request.(GetLeaderboardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLeaderboard")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetLeaderboardResponseObject); ok {
		return validResponse.VisitGetLeaderboardResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetPing operation middleware
func (sh *strictHandler) GetPing(ctx echo.Context) error {
	var request GetPingRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPing(ctx.Request().Context(), request.(GetPingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPing")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetPingResponseObject); ok {
		return validResponse.VisitGetPingResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCurrentUser operation middleware
func (sh *strictHandler) GetCurrentUser(ctx echo.Context) error {
	var request GetCurrentUserRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentUser(ctx.Request().Context(), request.(GetCurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCurrentUserResponseObject); ok {
		return validResponse.VisitGetCurrentUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ChangePassword operation middleware
func (sh *strictHandler) ChangePassword(ctx echo.Context) error {
	var request ChangePasswordRequestObject

	var body ChangePasswordJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ChangePassword(ctx.Request().Context(), request.(ChangePasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ChangePassword")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ChangePasswordResponseObject); ok {
		return validResponse.VisitChangePasswordResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateUserSettings operation middleware
func (sh *strictHandler) UpdateUserSettings(ctx echo.Context) error {
	var request UpdateUserSettingsRequestObject

	var body UpdateUserSettingsJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateUserSettings(ctx.Request().Context(), request.(UpdateUserSettingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateUserSettings")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateUserSettingsResponseObject); ok {
		return validResponse.VisitUpdateUserSettingsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SearchUsers operation middleware
func (sh *strictHandler) SearchUsers(ctx echo.Context, params SearchUsersParams) error {
	var request SearchUsersRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SearchUsers(ctx.Request().Context(), request.(SearchUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchUsers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SearchUsersResponseObject); ok {
		return validResponse.VisitSearchUsersResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetUserProfile operation middleware
func (sh *strictHandler) GetUserProfile(ctx echo.Context, userId openapi_types.UUID) error {
	var request GetUserProfileRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetUserProfile(ctx.Request().Context(), request.(GetUserProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetUserProfile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetUserProfileResponseObject); ok {
		return validResponse.VisitGetUserProfileResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbbVPjOPL/Kir9t+q/e2UID3NXs7wLAYbcsYEisHN3c1xKsTuOdmzJI8nDZqfy3a/0",
	"4KfEThwyZFh2XxFjWWr9+tetVqv1Bfs8TjgDpiQ++YIFyIQzCebhlAS38CkFqfSTz5kCZn6SJImoTxTl",
	"rPOL5Ez/T/pTiIn+9Z2ACT7B/9cpuu7Yt7JzLgQXeD6fezgA6Qua6E7wiR4LZYPNPdzjbBJRfwcD+9lI",
	"cw9fcDGmQQDs+Yed5EPNPTzg6oKnLHj+YQdcITvU3MN3nP9E2MzBLp9/9FuiAEU0pgp1kM95FPBHhoiv",
	"6GfQAt0zkqopF/Q32AEWldH0a/eF7rAbxJQNFbGoJIInIBS1ZjEmjEEwSiUI86xmCeATTJmCEISeh+KK",
	"RM0N5h4W8CmlQs/yQ6W1V+39wcs+5uNfwJLUiHYvQTRKRgxiEy5i/QsHRMGeojFgD7M0isg4AnyiRAp5",
	"71IJykLdewgssF2vwvSdbTX3MA0qY6UpDXBNt4LrMb9gYGms56ynhz1M9FxKsyw+0A0YiaGEX/ZyAT4z",
	"YN7cDVULXKqmt86/LWOn+Edr97WirAPE6GNZsbpL10GdRKckIsyvEYbEPLW8XyaX7m3UCvYFcbIPvaz7",
	"OpF6zir7bMKX5fIJG03TsCTYmPMIiPFimUGPJPicBQ22EdLPbeXX4vuwWfuYUEZZuEqGBVhygarD1cyn",
	"rn8vx6QOzTNCo9ktPBIRNDOPRAJIMBv5EaGxdXzL4K5iBIPH0big0nIDqQSQj6OAzNoA4oaqflYdpW6u",
	"1s8uU4YH0MpF93TDuYdjkJKELQzf9Fy0b5Sp5yTIfM/78+4/Rjfd4fD99e0Z9vD98Px21L26Pe+e/Wt0",
	"/s/+8G6IPdwf/Ny96p+NerfnZ+eDu373api1HVzfjS6u7wf64153oB8v79+NhudXF/o/19dXZ9fvB6Nu",
	"767/87npanh/cdHv9c8Hd6PT7lV30NP/fn97PXi3JMhpdzA4L/V82h2Mumc/9Qe1bvJd7q6z2cUk0qhM",
	"wPyo++bSGvCCmgQQtXrtWF4rNjHNZ7H4uqWg2Z6LKdZx5TINuzoSoWrWVxDXMbnRAjVCUpE4aQve4kqR",
	"f++5YRokvAAIGqR7sgI3XfI3UrttvGI1fyZmlNpvGEo08mdhKnUjrCXZFZAAxJgTEZwzJWbLepymoRzp",
	"oVg91cx7N3JQ30QQ9rEWaRtp6h62DS02CdCKuKOEU0kUrzznxQm62dRhWR8Dv+IAVk/4ikpV7wCeeeK7",
	"muCN4BMaQd3mZkWEs+nkv4KVtcQvTlVKolVjuRarR3ONjNlsaPWNGmzjDrbQ8Bq7rniABiPXsSv4qaBq",
	"NtQ6dHkpIAKE3s4ZXpini0wPf39/h91W3oTQ5m2hmKlSiU0GULfDqSYFbiKitE7RhAs0TcOQshBxNQWB",
	"zJYcPVI1RSJPZEgPOWJ6iLAA6YnoCSmqNOp6zZaISETQEMRn6gPq3vSxhz+DkHbEw/2D/QMNN0+AkYTi",
	"E3y8f7B/jD2cEDU1M+4YP9NJNPbG1M0ir63DZET6AT7B70CZ1MCNbuRVM3lHBwcb5VOqlifBF6DWs8C1",
	"q1HjUu5FgwECUYlI5JI/bw4Om+w3n0unmrPRHx2v/6hI65UJhU8+VKn0IfPm8wcPyzSOiV6f7T+Rhh59",
	"r0Aq/UML8YPpzWlGZqmilaqxCaUtdbPKwZVGqQHdvEVW1BcM+DtQyIIeEDk1sVImdAF4nlxbCfi9S6ol",
	"RJAYlPnkwxdMNRqfUhAzva81Hg4ba848B7GOYULSSOGTowMPx+RXGuul//BAP1Hmnrya3XT9AHwykdAw",
	"QrnLg5ouH7bkDFUQy1bksYmsXAQiBJnVcemGhJTpSBdFVCrEJ9Y9vmRe6dAJkShyjlw7eGfbhEG0RK7O",
	"F/2nH8w7Y8KstiJQsEy2ezYmFrd6omkvXtDAdorLntOmYgttrdv0Pjy3B3HZzOWMudTLILNp5p2pWn/x",
	"Zv0X+SHKU7hhdIiIoYYeMUlrvMrpH0nNZSUfrEe/dFb4mnhxWmJFo38oNh+1tLFYJwFR4DYguySQ0ckp",
	"D2YbcYcEAdWvSHRTCgUnJJLgbbXvnNcGh9U5zr8V8a2QKDW6etHcfwKVe1PCQnBs/n+JwkIj9bROiJSP",
	"XARtiH2TtX1V1C4jEJNfr4CFGuDDo7cmXsue365L7+b9POyA/dUptD5NaT5GqQv+7Hz+IJaSq6/ZVsqp",
	"knW2cl/kSV6RrZQRKNnK8VHFVI5NUkOB0DP97wey91t3798P7u/B3o+jh7981+og2wz18JIXk0zNvwcj",
	"0V/8uP6LvCrra1hVrkVrVamadiIeUgN/wmWNDV2Z1y/J8x+uSfw3G8Jha5J7u10+VvK9XEFTQ3mjICRT",
	"3wcpJ2mEPTw1B15GkiGovR7nHyksp11vYSJATpEpmUG+bVV2cotgzV/4klNkHQxpKxzndoHISF5FohcB",
	"ERKpKaBLpZJrFs2QsOiMyujsY2/ZPHTPLz98uOJhCAHiqSpxJZq1Z4vBKENlE84sakaLQFiA/OYOC825",
	"182qu5fQQnFIcUSlTLUrZPCIiEHADrqPBhx1HfmMhpCFBGVY7/+HLSneGc+dKzerCypydFxYURFsZXTx",
	"tbMS7aruaivp2nBrsICohTrYwBNxZdKa4mkeadfuJXOclTmnkrJwPZ1DKpXLW9Sut7euhUt6vbhcgldZ",
	"phu2KHEqFRoDert3ePQW+VMiiK9tw0N6AoQyRBSKgEiFOAMUgY5OPfM7oCFV9lhPP8oEfEqiog/sbbYr",
	"rMYGDdFiJu/x3vFRRVypiFD2+JHkYhrn5ebBtcexL6SHWBqPzQ/dJNWASZ8LkFWhnzU83zpyOdxZ5GJS",
	"nplFQPDEdWl3UczGwXrJYdhJutWnSG2W6iuaztSyeuVnDDGzIZrT0u79k5zt6m1LtaZn+VDST4UApgxm",
	"hSAau4DQaLYnTKFvsz/tRYTGpZLg58SxrvK4BlPTDFnBUVaA/OSF7KgFLRcvnWyhE4MnCkpTsNqYpqHs",
	"EFfLuYrPpZJPvIsT1sUS0xbnrJc8FdEMTdMQmcJQe26pg8xIL1lHb9CUp08+d93OHrRQGcz1YqFQ8DSB",
	"AI1n5h8l/WTV9XkObZWislsJr+HorXLDokbj2XtkCpR2rdfeFPyPxd0sqYhK3Vm59XsJoSvV2EmTUBBb",
	"cV/vBu9tgz+kTh04O0wGPp0KTk/oewFB6sMPBSvGMx0Ms0DvMirroKHEBGwR4wqvKy8Agq3rcv66WV3O",
	"w45cfF6j38K934KvIwqNGzK4fQs/LpaEyHU5pVJxsW4RvXStXiDAl2mIskl8qzXSjW+8aDmGLOFcXgTr",
	"veYQWHCZht/OW369zZieRoOqpMamsvnaaZ53o3KS3Qe8mgOIGE4pXqlLiYp7JatstXT95M+qyHb+ZunG",
	"TgunU/oGAVOCwrcJ0MusMDRZKCBfXItUKphEBEkaJxGgTChNNt/EhXRiYny5UL3tLTPtGarQTSjaogrd",
	"tntSFXolU6KngIAFCafMZlHcqX+8MknSsx4+T5o+U8jZdOzcKycptthCfOXquo1yK1bsMuDri5Hs8XKp",
	"DmkH6WoGj6PfWwqaR8HoyafbC6ZW6curwvHaSp18w6/fxcbNVVpUTKpaw5SblQSlKLMXwGrNqihZGmZN",
	"/6wqbe2MM8x2XwO0zbZfi1plT06TEnskEOFPG1fCoXm9wQWcT5UgsOSW/vamxg/9Ga42MzG/I9wmVHW3",
	"d2Ki/KkOeLa5xrPNzkazxd3MGc8WisMWC5OLK8JNQVj5JvEryC+Wp9N0MuZQsSfE217y22HklzYJb/vV",
	"EbpVWyoifII7JKGdz4d4/jD/XwAAAP//l49ClL1OAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
